import {GlobalStyle} from './globalStyle'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={GlobalStyle} lang="en">
      <body>{children}</body>
    </html>
  )
}
